# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home1/dilawars/Work/GITHUB/DILAWAR/tinyexpr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home1/dilawars/Work/GITHUB/DILAWAR/tinyexpr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Devel\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home1/dilawars/Work/GITHUB/DILAWAR/tinyexpr/CMakeFiles /home1/dilawars/Work/GITHUB/DILAWAR/tinyexpr/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home1/dilawars/Work/GITHUB/DILAWAR/tinyexpr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyexpr_example_uppercase

# Build rule for target.
tinyexpr_example_uppercase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyexpr_example_uppercase
.PHONY : tinyexpr_example_uppercase

# fast build rule for target.
tinyexpr_example_uppercase/fast:
	$(MAKE) -f CMakeFiles/tinyexpr_example_uppercase.dir/build.make CMakeFiles/tinyexpr_example_uppercase.dir/build
.PHONY : tinyexpr_example_uppercase/fast

#=============================================================================
# Target rules for targets named tinyexpr_example2

# Build rule for target.
tinyexpr_example2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyexpr_example2
.PHONY : tinyexpr_example2

# fast build rule for target.
tinyexpr_example2/fast:
	$(MAKE) -f CMakeFiles/tinyexpr_example2.dir/build.make CMakeFiles/tinyexpr_example2.dir/build
.PHONY : tinyexpr_example2/fast

#=============================================================================
# Target rules for targets named tinyexpr_example3

# Build rule for target.
tinyexpr_example3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyexpr_example3
.PHONY : tinyexpr_example3

# fast build rule for target.
tinyexpr_example3/fast:
	$(MAKE) -f CMakeFiles/tinyexpr_example3.dir/build.make CMakeFiles/tinyexpr_example3.dir/build
.PHONY : tinyexpr_example3/fast

#=============================================================================
# Target rules for targets named tinyexpr

# Build rule for target.
tinyexpr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyexpr
.PHONY : tinyexpr

# fast build rule for target.
tinyexpr/fast:
	$(MAKE) -f CMakeFiles/tinyexpr.dir/build.make CMakeFiles/tinyexpr.dir/build
.PHONY : tinyexpr/fast

#=============================================================================
# Target rules for targets named tinyexpr_test

# Build rule for target.
tinyexpr_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyexpr_test
.PHONY : tinyexpr_test

# fast build rule for target.
tinyexpr_test/fast:
	$(MAKE) -f CMakeFiles/tinyexpr_test.dir/build.make CMakeFiles/tinyexpr_test.dir/build
.PHONY : tinyexpr_test/fast

#=============================================================================
# Target rules for targets named tinyexpr_test_pr

# Build rule for target.
tinyexpr_test_pr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyexpr_test_pr
.PHONY : tinyexpr_test_pr

# fast build rule for target.
tinyexpr_test_pr/fast:
	$(MAKE) -f CMakeFiles/tinyexpr_test_pr.dir/build.make CMakeFiles/tinyexpr_test_pr.dir/build
.PHONY : tinyexpr_test_pr/fast

#=============================================================================
# Target rules for targets named tinyexpr_benchmark

# Build rule for target.
tinyexpr_benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyexpr_benchmark
.PHONY : tinyexpr_benchmark

# fast build rule for target.
tinyexpr_benchmark/fast:
	$(MAKE) -f CMakeFiles/tinyexpr_benchmark.dir/build.make CMakeFiles/tinyexpr_benchmark.dir/build
.PHONY : tinyexpr_benchmark/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) -f CMakeFiles/examples.dir/build.make CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named tinyexpr_example

# Build rule for target.
tinyexpr_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyexpr_example
.PHONY : tinyexpr_example

# fast build rule for target.
tinyexpr_example/fast:
	$(MAKE) -f CMakeFiles/tinyexpr_example.dir/build.make CMakeFiles/tinyexpr_example.dir/build
.PHONY : tinyexpr_example/fast

benchmark.o: benchmark.c.o

.PHONY : benchmark.o

# target to build an object file
benchmark.c.o:
	$(MAKE) -f CMakeFiles/tinyexpr_benchmark.dir/build.make CMakeFiles/tinyexpr_benchmark.dir/benchmark.c.o
.PHONY : benchmark.c.o

benchmark.i: benchmark.c.i

.PHONY : benchmark.i

# target to preprocess a source file
benchmark.c.i:
	$(MAKE) -f CMakeFiles/tinyexpr_benchmark.dir/build.make CMakeFiles/tinyexpr_benchmark.dir/benchmark.c.i
.PHONY : benchmark.c.i

benchmark.s: benchmark.c.s

.PHONY : benchmark.s

# target to generate assembly for a file
benchmark.c.s:
	$(MAKE) -f CMakeFiles/tinyexpr_benchmark.dir/build.make CMakeFiles/tinyexpr_benchmark.dir/benchmark.c.s
.PHONY : benchmark.c.s

example.o: example.c.o

.PHONY : example.o

# target to build an object file
example.c.o:
	$(MAKE) -f CMakeFiles/tinyexpr_example.dir/build.make CMakeFiles/tinyexpr_example.dir/example.c.o
.PHONY : example.c.o

example.i: example.c.i

.PHONY : example.i

# target to preprocess a source file
example.c.i:
	$(MAKE) -f CMakeFiles/tinyexpr_example.dir/build.make CMakeFiles/tinyexpr_example.dir/example.c.i
.PHONY : example.c.i

example.s: example.c.s

.PHONY : example.s

# target to generate assembly for a file
example.c.s:
	$(MAKE) -f CMakeFiles/tinyexpr_example.dir/build.make CMakeFiles/tinyexpr_example.dir/example.c.s
.PHONY : example.c.s

example2.o: example2.c.o

.PHONY : example2.o

# target to build an object file
example2.c.o:
	$(MAKE) -f CMakeFiles/tinyexpr_example2.dir/build.make CMakeFiles/tinyexpr_example2.dir/example2.c.o
.PHONY : example2.c.o

example2.i: example2.c.i

.PHONY : example2.i

# target to preprocess a source file
example2.c.i:
	$(MAKE) -f CMakeFiles/tinyexpr_example2.dir/build.make CMakeFiles/tinyexpr_example2.dir/example2.c.i
.PHONY : example2.c.i

example2.s: example2.c.s

.PHONY : example2.s

# target to generate assembly for a file
example2.c.s:
	$(MAKE) -f CMakeFiles/tinyexpr_example2.dir/build.make CMakeFiles/tinyexpr_example2.dir/example2.c.s
.PHONY : example2.c.s

example3.o: example3.c.o

.PHONY : example3.o

# target to build an object file
example3.c.o:
	$(MAKE) -f CMakeFiles/tinyexpr_example3.dir/build.make CMakeFiles/tinyexpr_example3.dir/example3.c.o
.PHONY : example3.c.o

example3.i: example3.c.i

.PHONY : example3.i

# target to preprocess a source file
example3.c.i:
	$(MAKE) -f CMakeFiles/tinyexpr_example3.dir/build.make CMakeFiles/tinyexpr_example3.dir/example3.c.i
.PHONY : example3.c.i

example3.s: example3.c.s

.PHONY : example3.s

# target to generate assembly for a file
example3.c.s:
	$(MAKE) -f CMakeFiles/tinyexpr_example3.dir/build.make CMakeFiles/tinyexpr_example3.dir/example3.c.s
.PHONY : example3.c.s

example_uppercase.o: example_uppercase.c.o

.PHONY : example_uppercase.o

# target to build an object file
example_uppercase.c.o:
	$(MAKE) -f CMakeFiles/tinyexpr_example_uppercase.dir/build.make CMakeFiles/tinyexpr_example_uppercase.dir/example_uppercase.c.o
.PHONY : example_uppercase.c.o

example_uppercase.i: example_uppercase.c.i

.PHONY : example_uppercase.i

# target to preprocess a source file
example_uppercase.c.i:
	$(MAKE) -f CMakeFiles/tinyexpr_example_uppercase.dir/build.make CMakeFiles/tinyexpr_example_uppercase.dir/example_uppercase.c.i
.PHONY : example_uppercase.c.i

example_uppercase.s: example_uppercase.c.s

.PHONY : example_uppercase.s

# target to generate assembly for a file
example_uppercase.c.s:
	$(MAKE) -f CMakeFiles/tinyexpr_example_uppercase.dir/build.make CMakeFiles/tinyexpr_example_uppercase.dir/example_uppercase.c.s
.PHONY : example_uppercase.c.s

test.o: test.c.o

.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) -f CMakeFiles/tinyexpr_test.dir/build.make CMakeFiles/tinyexpr_test.dir/test.c.o
	$(MAKE) -f CMakeFiles/tinyexpr_test_pr.dir/build.make CMakeFiles/tinyexpr_test_pr.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i

.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) -f CMakeFiles/tinyexpr_test.dir/build.make CMakeFiles/tinyexpr_test.dir/test.c.i
	$(MAKE) -f CMakeFiles/tinyexpr_test_pr.dir/build.make CMakeFiles/tinyexpr_test_pr.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s

.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) -f CMakeFiles/tinyexpr_test.dir/build.make CMakeFiles/tinyexpr_test.dir/test.c.s
	$(MAKE) -f CMakeFiles/tinyexpr_test_pr.dir/build.make CMakeFiles/tinyexpr_test_pr.dir/test.c.s
.PHONY : test.c.s

tinyexpr.o: tinyexpr.c.o

.PHONY : tinyexpr.o

# target to build an object file
tinyexpr.c.o:
	$(MAKE) -f CMakeFiles/tinyexpr.dir/build.make CMakeFiles/tinyexpr.dir/tinyexpr.c.o
.PHONY : tinyexpr.c.o

tinyexpr.i: tinyexpr.c.i

.PHONY : tinyexpr.i

# target to preprocess a source file
tinyexpr.c.i:
	$(MAKE) -f CMakeFiles/tinyexpr.dir/build.make CMakeFiles/tinyexpr.dir/tinyexpr.c.i
.PHONY : tinyexpr.c.i

tinyexpr.s: tinyexpr.c.s

.PHONY : tinyexpr.s

# target to generate assembly for a file
tinyexpr.c.s:
	$(MAKE) -f CMakeFiles/tinyexpr.dir/build.make CMakeFiles/tinyexpr.dir/tinyexpr.c.s
.PHONY : tinyexpr.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... tinyexpr_example_uppercase"
	@echo "... edit_cache"
	@echo "... tinyexpr_example2"
	@echo "... install"
	@echo "... tinyexpr_example3"
	@echo "... tinyexpr"
	@echo "... tinyexpr_test"
	@echo "... tinyexpr_test_pr"
	@echo "... install/local"
	@echo "... test"
	@echo "... tinyexpr_benchmark"
	@echo "... examples"
	@echo "... tinyexpr_example"
	@echo "... benchmark.o"
	@echo "... benchmark.i"
	@echo "... benchmark.s"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... example2.o"
	@echo "... example2.i"
	@echo "... example2.s"
	@echo "... example3.o"
	@echo "... example3.i"
	@echo "... example3.s"
	@echo "... example_uppercase.o"
	@echo "... example_uppercase.i"
	@echo "... example_uppercase.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... tinyexpr.o"
	@echo "... tinyexpr.i"
	@echo "... tinyexpr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

